#ifndef NULLSPACE_NET_PROTOCOL_H_
#define NULLSPACE_NET_PROTOCOL_H_

namespace null {

enum class ProtocolCore {
  EncryptionRequest = 0x01,
  EncryptionResponse,
  ReliableMessage,
  ReliableAck,
  SyncTimeRequest,
  SyncTimeResponse,
  Disconnect,
  SmallChunkBody,
  SmallChunkTail,
  HugeChunk,
  HugeChunkCancel,
  HugeChunkCancelAck,
  NoOp,
  PacketCluster,
  Unknown1,
  ContinuumEncryptionResponse,
  ContinuumEncryptionRequest,
  ContinuumKeyExpansionRequest,
  ContinuumKeyExpansionResponse,

  Count
};

enum class ProtocolC2S {
  Core = 0x00,
  ArenaLogin,
  LeaveArena,
  Position,
  Unknown1,
  DeathMessage,
  ChatMessage,
  TakePrize,
  SpectatePlayer,
  VIEPassword,
  Unknown2,
  RequestExe,
  MapRequest,
  NewsRequest,
  Voice,
  FrequencyChange,
  AttachRequest,
  Unknown3,
  Unknown4,
  FlagRequest,
  DropAttached,
  DropFlags,
  FileTransfer,
  RegistrationResponse,
  SetShip,
  SetBanner,
  Security,
  SecurityViolation,
  DropBrick,
  ChangeArenaSettings,
  EndKothTimer,
  FireBall,
  BallRequest,
  SoccerGoalScored,
  SecurityViolation2,
  Unknown5,
  Password,
  WatchDamage = 0x32,
  ToggleLVZ = 0x35,
  ModifyLVZ = 0x36,

  Count
};

enum class ProtocolS2C {
  Core = 0x00,
  PlayerId,
  JoinGame,
  PlayerEntering,
  PlayerLeaving,
  LargePosition,
  PlayerDeath,
  Chat,
  PlayerPrize,
  ScoreUpdate,
  PasswordResponse,
  SoccerGoal,
  Voice,
  FrequencyChange,
  CreateTurret,
  ArenaSettings,
  FileTransfer,
  Unknown1,
  FlagPosition,
  FlagClaim,
  FlagVictory,
  DestroyTurret,
  DropFlag,
  Unknown2,
  Security,
  RequestFile,
  ResetScore,
  ShipReset,
  Spectate,
  TeamAndShipChange,
  PersonalBannerChange,
  PlayerBannerChange,
  CollectedPrize,
  BrickDropped,
  TurfFlagUpdate,
  FlagReward,
  SpeedGameOver,
  ToggleUFO,
  Unknown3,
  KeepAlive,
  SmallPosition,
  MapInformation,
  CompressedMap,
  SetPersonalKothTimer,
  KothGameReset,
  AddKothTime,
  PowerballPosition,
  ArenaDirectoryListing,
  ZoneBannerAdvertisement,
  PostLogin,
  SetCoordinates,
  LoginFailure,
  Version,
  ToggleLVZ,
  ModifyLVZ,
  ToggleSendDamage,
  WatchDamage,
  BatchedSmallPosition,
  BatchedLargePosition,
  Redirect = 0x3B,
  SelectBox = 0x3C,

  Count
};

}  // namespace null

#endif
